# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
import h_rc

from PyQt5.QtWidgets import QDialog, QDialogButtonBox, QVBoxLayout, QLabel

dados = []
global sub
global add
global mult
sub = 0
add = 0
mult = 1
demais = "Too many dice! (Don't worry, they'll still be accounted for.)"  

class caixaFinal(QDialog):
    def __init__(self,formula,formulaString,dados):
        super().__init__()
        QtGui.QFontDatabase.addApplicationFont(":/fonts/minecraft_font.ttf")
        self.setWindowFlags(QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowTitleHint)
        self.setWindowTitle("Result")
        self.resize(376, 270)
        self.setMinimumSize(QtCore.QSize(376, 270))
        self.setMaximumSize(QtCore.QSize(376, 270))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/based.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setStyleSheet("background-color: rgb(15, 15, 15);")

        botaoOk = QtWidgets.QPushButton()
        botaoOk.setGeometry(QtCore.QRect(130, 220, 101, 31))
        botaoOk.setStyleSheet(
                "color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
                "font: 11pt \"Minecraft\";")
        botaoOk.setObjectName("botaoOk")
        botaoOk.setText("Ok!")
        botaoOk.clicked.connect(self.close)

        labelResult = QtWidgets.QLabel()
        labelResult.setGeometry(QtCore.QRect(20, 30, 331, 21))
        labelResult.setStyleSheet(
                "color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
                "font: 11pt \"Minecraft\";")
        labelResult.setObjectName("labelResult")
        labelResult.setText(f"Result: {formula}")

        labelAlunos = QtWidgets.QLabel()
        labelAlunos.setGeometry(QtCore.QRect(20, 30, 331, 21))
        labelAlunos.setStyleSheet(
                "color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
                "font: 8pt \"Minecraft\";")
        labelAlunos.setObjectName("labelAlunos")
        labelAlunos.setText(f"Created by: CalmMagma#1274")

        labelFormula = QtWidgets.QTextEdit()
        labelFormula.setGeometry(QtCore.QRect(20, 80, 331, 101))
        labelFormula.setMinimumSize(QtCore.QSize(331, 101))
        labelFormula.setMaximumSize(QtCore.QSize(331, 101))
        labelFormula.setAcceptRichText(True)
        labelFormula.setReadOnly(True)
        labelFormula.setStyleSheet(
                "color: rgb(255, 0, 255);\n"
                "font: 9pt \"Minecraft\";""border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n")
        labelFormula.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        labelFormula.setObjectName("labelFormula")
        labelFormula.setText(f"Formula: {formulaString}")

        self.layout = QVBoxLayout()
        self.layout.addWidget(labelFormula)
        self.layout.addWidget(labelResult)
        self.layout.addWidget(labelAlunos)
        self.layout.addWidget(botaoOk)
        self.setLayout(self.layout)

class Ui_janelaDados(object):
    def setupUi(self, janelaDados):
        janelaDados.setObjectName("janelaDados")
        janelaDados.resize(697, 434)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(janelaDados.sizePolicy().hasHeightForWidth())
        janelaDados.setSizePolicy(sizePolicy)
        janelaDados.setMinimumSize(QtCore.QSize(697, 434))
        janelaDados.setMaximumSize(QtCore.QSize(697, 434))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/based.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        janelaDados.setWindowIcon(icon)
        janelaDados.setStyleSheet("background-color: rgb(15, 15, 15);")
        janelaDados.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        QtGui.QFontDatabase.addApplicationFont(":/fonts/minecraft_font.ttf")
        self.centralwidget = QtWidgets.QWidget(janelaDados)
        self.centralwidget.setObjectName("centralwidget")
        self.tituloPainel = QtWidgets.QLabel(self.centralwidget)
        self.tituloPainel.setGeometry(QtCore.QRect(275, 0, 101, 51))
        self.tituloPainel.setStyleSheet("font: 16pt \"Minecraft\";\n"
"color: rgb(85, 255, 255);\n"
"\n"
"")
        self.tituloPainel.setObjectName("tituloPainel")
        self.tituloDados = QtWidgets.QLabel(self.centralwidget)
        self.tituloDados.setGeometry(QtCore.QRect(335, -10, 101, 70))
        self.tituloDados.setStyleSheet("color: rgb(255, 0, 255);\n"
"font: 16pt \"Minecraft\";")
        self.tituloDados.setObjectName("tituloDados")
        self.botaoMoeda = QtWidgets.QPushButton(self.centralwidget)
        self.botaoMoeda.setGeometry(QtCore.QRect(30, 90, 111, 111))
        self.botaoMoeda.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"image: url(:/dice/d2rosa.png);")
        self.botaoMoeda.setText("")
        self.botaoMoeda.setObjectName("botaoMoeda")
        self.botaoD3 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD3.setGeometry(QtCore.QRect(160, 90, 111, 111))
        self.botaoD3.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 10px;\n"
"image: url(:/dice/d3rosa.png);")
        self.botaoD3.setText("")
        self.botaoD3.setObjectName("botaoD3")
        self.botaoD4 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD4.setEnabled(True)
        self.botaoD4.setGeometry(QtCore.QRect(290, 90, 111, 111))
        self.botaoD4.setWhatsThis("")
        self.botaoD4.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"image: url(:/dice/d4rosa.png);\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;")
        self.botaoD4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.botaoD4.setText("")
        self.botaoD4.setCheckable(False)
        self.botaoD4.setObjectName("botaoD4")
        self.botaoD6 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD6.setGeometry(QtCore.QRect(420, 90, 111, 111))
        self.botaoD6.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"image: url(:/dice/d6rosa.png);\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;")
        self.botaoD6.setText("")
        self.botaoD6.setObjectName("botaoD6")
        self.botaoD8 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD8.setGeometry(QtCore.QRect(550, 90, 111, 111))
        self.botaoD8.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"image: url(:/dice/d8rosa.png);\n"
"")
        self.botaoD8.setText("")
        self.botaoD8.setObjectName("botaoD8")
        self.botaoD20 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD20.setGeometry(QtCore.QRect(290, 230, 111, 111))
        self.botaoD20.setStyleSheet("image: url(:/dice/d20rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")
        self.botaoD20.setText("")
        self.botaoD20.setObjectName("botaoD20")
        self.botaoD10 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD10.setGeometry(QtCore.QRect(30, 230, 111, 111))
        self.botaoD10.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"image: url(:/dice/d10rosa.png);")
        self.botaoD10.setText("")
        self.botaoD10.setObjectName("botaoD10")
        self.botaoD12 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD12.setGeometry(QtCore.QRect(160, 230, 111, 111))
        self.botaoD12.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"image: url(:/dice/d12rosa.png);")
        self.botaoD12.setText("")
        self.botaoD12.setObjectName("botaoD12")
        self.botaoD100 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD100.setGeometry(QtCore.QRect(420, 230, 111, 111))
        self.botaoD100.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"image: url(:/dice/d100drosa.png);")
        self.botaoD100.setText("")
        self.botaoD100.setObjectName("botaoD100")
        self.iconeCaveleiro = QtWidgets.QGraphicsView(self.centralwidget)
        self.iconeCaveleiro.setGeometry(QtCore.QRect(440, -1, 61, 81))
        self.iconeCaveleiro.setStyleSheet("border-image: url(:/icons/cavaloroxo.png);")
        self.iconeCaveleiro.setObjectName("iconeCaveleiro")
        self.iconeMago = QtWidgets.QGraphicsView(self.centralwidget)
        self.iconeMago.setGeometry(QtCore.QRect(174, 2, 61, 81))
        self.iconeMago.setStyleSheet("border-image: url(:/icons/elmagoprior.png);")
        self.iconeMago.setObjectName("iconeMago")
        self.iconeMenos = QtWidgets.QGraphicsView(self.centralwidget)
        self.iconeMenos.setGeometry(QtCore.QRect(200, 404, 31, 31))
        self.iconeMenos.setStyleSheet("border-image: url(:/icons/subtrativo.png);")
        self.iconeMenos.setObjectName("iconeMenos")
        self.campoMenos = QtWidgets.QLineEdit(self.centralwidget)
        self.campoMenos.setGeometry(QtCore.QRect(236, 409, 113, 21))
        self.campoMenos.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"color: rgb(85, 255, 255)")
        self.campoMenos.setObjectName("campoMenos")
        self.tituloModifc = QtWidgets.QLabel(self.centralwidget)
        self.tituloModifc.setGeometry(QtCore.QRect(43, 408, 91, 21))
        self.tituloModifc.setStyleSheet("font: 16pt \"Minecraft\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));")
        self.tituloModifc.setObjectName("tituloModifc")
        self.campoMais = QtWidgets.QLineEdit(self.centralwidget)
        self.campoMais.setGeometry(QtCore.QRect(406, 409, 113, 21))
        self.campoMais.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"color: rgb(85, 255, 255)")
        self.campoMais.setObjectName("campoMais")
        self.iconeMais = QtWidgets.QGraphicsView(self.centralwidget)
        self.iconeMais.setGeometry(QtCore.QRect(370, 404, 31, 31))
        self.iconeMais.setStyleSheet("border-image: url(:/icons/aditivo.png);")
        self.iconeMais.setObjectName("iconeMais")
        self.campoVezes = QtWidgets.QLineEdit(self.centralwidget)
        self.campoVezes.setGeometry(QtCore.QRect(576, 409, 113, 21))
        self.campoVezes.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"color: rgb(85, 255, 255)")
        self.campoVezes.setObjectName("campoVezes")
        self.iconeVezes = QtWidgets.QGraphicsView(self.centralwidget)
        self.iconeVezes.setGeometry(QtCore.QRect(540, 404, 31, 31))
        self.iconeVezes.setStyleSheet("border-image: url(:/icons/multiplicativo.png);")
        self.iconeVezes.setObjectName("iconeVezes")
        self.tituloAdores = QtWidgets.QLabel(self.centralwidget)
        self.tituloAdores.setGeometry(QtCore.QRect(96, 408, 101, 21))
        self.tituloAdores.setStyleSheet("color:rgb(85, 255, 255);\n"
"font: 16pt \"Minecraft\";")
        self.tituloAdores.setObjectName("tituloAdores")
        self.botaoD100_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoD100_2.setGeometry(QtCore.QRect(550, 230, 111, 111))
        self.botaoD100_2.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"image: url(:/dice/d100rosa.png);")
        self.botaoD100_2.setText("")
        self.botaoD100_2.setObjectName("botaoD100_2")
        self.tituloP = QtWidgets.QLabel(self.centralwidget)
        self.tituloP.setGeometry(QtCore.QRect(330, 41, 16, 20))
        self.tituloP.setStyleSheet("font: 16pt \"Minecraft\";\n"
"color: rgb(180, 74, 255);")
        self.tituloP.setObjectName("tituloP")
        self.tituloG = QtWidgets.QLabel(self.centralwidget)
        self.tituloG.setGeometry(QtCore.QRect(345, 41, 20, 21))
        self.tituloG.setStyleSheet("font: 16pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.tituloG.setObjectName("tituloG")
        self.tituloR = QtWidgets.QLabel(self.centralwidget)
        self.tituloR.setGeometry(QtCore.QRect(314, 41, 16, 20))
        self.tituloR.setStyleSheet("font: 16pt \"Minecraft\";\n"
"color: rgb(0, 255, 255);")
        self.tituloR.setObjectName("tituloR")
        self.labelD2 = QtWidgets.QLabel(self.centralwidget)
        self.labelD2.setGeometry(QtCore.QRect(70, 205, 31, 21))
        self.labelD2.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD2.setObjectName("labelD2")
        self.labelD3 = QtWidgets.QLabel(self.centralwidget)
        self.labelD3.setGeometry(QtCore.QRect(200, 205, 31, 21))
        self.labelD3.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD3.setObjectName("labelD3")
        self.labelD4 = QtWidgets.QLabel(self.centralwidget)
        self.labelD4.setGeometry(QtCore.QRect(330, 205, 31, 21))
        self.labelD4.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD4.setObjectName("labelD4")
        self.labelD6 = QtWidgets.QLabel(self.centralwidget)
        self.labelD6.setGeometry(QtCore.QRect(460, 205, 31, 21))
        self.labelD6.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD6.setObjectName("labelD6")
        self.labelD8 = QtWidgets.QLabel(self.centralwidget)
        self.labelD8.setGeometry(QtCore.QRect(590, 205, 31, 21))
        self.labelD8.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD8.setObjectName("labelD8")
        self.labelD10 = QtWidgets.QLabel(self.centralwidget)
        self.labelD10.setGeometry(QtCore.QRect(65, 345, 41, 21))
        self.labelD10.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD10.setObjectName("labelD10")
        self.labelD12 = QtWidgets.QLabel(self.centralwidget)
        self.labelD12.setGeometry(QtCore.QRect(195, 345, 41, 20))
        self.labelD12.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD12.setObjectName("labelD12")
        self.labelD20 = QtWidgets.QLabel(self.centralwidget)
        self.labelD20.setGeometry(QtCore.QRect(325, 345, 41, 20))
        self.labelD20.setStyleSheet("font: 14pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelD20.setObjectName("labelD20")
        self.labelDez = QtWidgets.QLabel(self.centralwidget)
        self.labelDez.setGeometry(QtCore.QRect(429, 345, 111, 20))
        self.labelDez.setStyleSheet("font: 8pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelDez.setObjectName("labelDez")
        self.labelAbs = QtWidgets.QLabel(self.centralwidget)
        self.labelAbs.setGeometry(QtCore.QRect(554, 345, 111, 20))
        self.labelAbs.setStyleSheet("font: 8pt \"Minecraft\";\n"
"color: rgb(255, 0, 255);")
        self.labelAbs.setObjectName("labelAbs")
        self.botaoGirar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoGirar.setObjectName("botaoGirar")
        self.botaoGirar.setGeometry(QtCore.QRect(10, 375, 121, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.botaoGirar.setPalette(palette)
        self.botaoGirar.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n""color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"font: 11pt \"Minecraft\";")
        self.labelFormula = QtWidgets.QLabel(self.centralwidget)
        self.labelFormula.setObjectName("labelFormula")
        self.labelFormula.setGeometry(QtCore.QRect(135, 377, 551, 16))
        self.labelFormula.setStyleSheet("font: 10pt \"Minecraft\";\n"
"color: rgb(0, 255, 255)")
        
        self.botaoD20.raise_()
        self.iconeCaveleiro.raise_()
        self.tituloPainel.raise_()
        self.tituloDados.raise_()
        self.botaoMoeda.raise_()
        self.botaoD3.raise_()
        self.botaoD4.raise_()
        self.botaoD6.raise_()
        self.botaoD8.raise_()
        self.botaoD10.raise_()
        self.botaoD12.raise_()
        self.botaoD100.raise_()
        self.iconeMago.raise_()
        self.iconeMenos.raise_()
        self.campoMenos.raise_()
        self.tituloModifc.raise_()
        self.campoMais.raise_()
        self.iconeMais.raise_()
        self.campoVezes.raise_()
        self.iconeVezes.raise_()
        self.tituloAdores.raise_()
        self.botaoD100_2.raise_()
        self.tituloP.raise_()
        self.tituloG.raise_()
        self.tituloR.raise_()
        self.labelD2.raise_()
        self.labelD3.raise_()
        self.labelD4.raise_()
        self.labelD6.raise_()
        self.labelD8.raise_()
        self.labelD10.raise_()
        self.labelD12.raise_()
        self.labelD20.raise_()
        self.labelDez.raise_()
        self.labelAbs.raise_()
        self.botaoGirar.raise_()
        self.labelFormula.raise_()
        janelaDados.setCentralWidget(self.centralwidget)

        self.retranslateUi(janelaDados)
        QtCore.QMetaObject.connectSlotsByName(janelaDados)
        
        #D2
        self.botaoMoeda.pressed.connect(self.d2press)
        self.botaoMoeda.released.connect(self.d2release)
        self.botaoMoeda.clicked.connect(self.d2click)
        
        #D3
        self.botaoD3.pressed.connect(self.d3press)
        self.botaoD3.released.connect(self.d3release)
        self.botaoD3.clicked.connect(self.d3click)
        
        #D4
        self.botaoD4.pressed.connect(self.d4press)
        self.botaoD4.released.connect(self.d4release)
        self.botaoD4.clicked.connect(self.d4click)
        
        #D6
        self.botaoD6.pressed.connect(self.d6press)
        self.botaoD6.released.connect(self.d6release)
        self.botaoD6.clicked.connect(self.d6click)
        
        #D8
        self.botaoD8.pressed.connect(self.d8press)
        self.botaoD8.released.connect(self.d8release)
        self.botaoD8.clicked.connect(self.d8click)
        
        #D10
        self.botaoD10.pressed.connect(self.d10press)
        self.botaoD10.released.connect(self.d10release)
        self.botaoD10.clicked.connect(self.d10click)
        
        #D12
        self.botaoD12.pressed.connect(self.d12press)
        self.botaoD12.released.connect(self.d12release)
        self.botaoD12.clicked.connect(self.d12click)
        
        #D20
        self.botaoD20.pressed.connect(self.d20press)
        self.botaoD20.released.connect(self.d20release)
        self.botaoD20.clicked.connect(self.d20click)
        
        #D100DEC
        self.botaoD100.pressed.connect(self.d100Dpress)
        self.botaoD100.released.connect(self.d100Drelease)
        self.botaoD100.clicked.connect(self.d100Dclick)
        
        #D100ABS
        self.botaoD100_2.pressed.connect(self.d100Apress)
        self.botaoD100_2.released.connect(self.d100Arelease)
        self.botaoD100_2.clicked.connect(self.d100Aclick)
        
        #SUBTRAÇÃO
        self.campoMenos.textEdited.connect(self.modMenos)
        
        #ADIÇÃO
        self.campoMais.textEdited.connect(self.modMais)
        
        #MULTIPLICAÇÃO
        self.campoVezes.textEdited.connect(self.modVezes)
        
        #RODAR
        self.botaoGirar.clicked.connect(self.girarclick)
        self.botaoGirar.pressed.connect(self.girarpress)
        self.botaoGirar.released.connect(self.girarrelease)
        

    def retranslateUi(self, janelaDados):
        _translate = QtCore.QCoreApplication.translate
        janelaDados.setWindowTitle(_translate("janelaDados", "Dice Roller"))
        self.tituloPainel.setText(_translate("janelaDados", "Dice"))
        self.tituloDados.setText(_translate("janelaDados", "Roller"))
        self.botaoD4.setToolTip(_translate("janelaDados", "<html><head/><body><p><span style=\" font-size:10pt;\">Gira um dado de 20 lados.</span></p></body></html>"))
        self.tituloModifc.setText(_translate("janelaDados", "Modi"))
        self.tituloAdores.setText(_translate("janelaDados", "fiers"))
        self.tituloP.setText(_translate("janelaDados", "P"))
        self.tituloG.setText(_translate("janelaDados", "G"))
        self.tituloR.setText(_translate("janelaDados", "R"))
        self.labelD2.setText(_translate("janelaDados", "D2"))
        self.labelD3.setText(_translate("janelaDados", "D3"))
        self.labelD4.setText(_translate("janelaDados", "D4"))
        self.labelD6.setText(_translate("janelaDados", "D6"))
        self.labelD8.setText(_translate("janelaDados", "D8"))
        self.labelD10.setText(_translate("janelaDados", "D10"))
        self.labelD12.setText(_translate("janelaDados", "D12"))
        self.labelD20.setText(_translate("janelaDados", "D20"))
        self.labelDez.setText(_translate("janelaDados", "D100 (dozens)"))
        self.labelAbs.setText(_translate("janelaDados", "D100 (absolute)"))
        self.botaoGirar.setText(_translate("janelaDados", "Roll Dice"))
        self.labelFormula.setText(_translate("janelaDados", "Dice: "))
        
    #------------------------- MODIFICADORES -------------------------#
    #SUBTRAÇÃO
    def modMenos(self):
        global sub
        if self.campoMenos.text().isdigit():
            sub = int(self.campoMenos.text())
        elif self.campoMenos.text() == "":
            sub = 0
        else:
            self.campoMenos.setText("")
            sub = 0

    #ADIÇÃO
    def modMais(self):
        global add
        if self.campoMais.text().isdigit():
            add = int(self.campoMais.text())
        elif self.campoMais.text() == "":
            add = 0
        else:
            self.campoMais.setText("")
            add = 0

    #MULTIPLICAÇÃO
    def modVezes(self):
        global mult
        if self.campoVezes.text().isdigit():
            mult = int(self.campoVezes.text())
        elif self.campoVezes.text() == "":
            mult = 1
        else:
            self.campoVezes.setText("")
            mult = 1

    #------------------------- RODAR -------------------------#
    def girarpress(self):
        self.botaoGirar.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n""color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"font: 11pt \"Minecraft\";")
    def girarrelease(self):
        self.botaoGirar.setStyleSheet("border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n""color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"font: 11pt \"Minecraft\";")
    def girarclick(self):
        global mult
        global add
        global sub
        formulaString = str(mult) + " * "
        formula = 0
        if not dados:
                formulaString += "0 + "
        for item in dados:
                if item == "d2":
                        h = random.randint(1,2)
                        formula += h
                        formulaString += f"D2({h}) + "
                elif item == "d3":
                        h = random.randint(1,3)
                        formula += h
                        formulaString += f"D3({h}) + "
                elif item == "d4":
                        h = random.randint(1,4)
                        formula += h
                        formulaString += f"D4({h}) + "
                elif item == "d6":
                        h = random.randint(1,6)
                        formula += h
                        formulaString += f"D6({h}) + "
                elif item == "d8":
                        h = random.randint(1,8)
                        formula += h
                        formulaString += f"D8({h}) + "
                elif item == "d10":
                        h = random.randint(1,10)
                        formula += h
                        formulaString += f"D10({h}) + "
                elif item == "d12":
                        h = random.randint(1,12)
                        formula += h
                        formulaString += f"D12({h}) + "
                elif item == "d20":
                        h = random.randint(1,20)
                        formula += h
                        formulaString += f"D20({h}) + "
                elif item == "d100d":
                        h = random.randint(1,10) * 10
                        formula += h
                        formulaString += f"D100Dec({h}) + "
                elif item == "d100a":
                        h = random.randint(1,100)
                        formula += h
                        formulaString += f"D100Abs({h}) + "
                else:
                        pass
        formula *= mult
        formula += add
        formula -= sub
        formulaString += f"{add} - {sub}"
        dados.clear()
        self.labelFormula.setText("Dice: ")

        #chama a caixa de diálogo
        dlg = caixaFinal(formula,formulaString,dados)
        dlg.exec()


    #------------------------- DADOS -------------------------#        
    #D2
    def d2click(self):
        dados.append("d2")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D2 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D2 ")

    def d2press(self):
        self.botaoMoeda.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d2cyan.png);")

    def d2release(self):
        self.botaoMoeda.setStyleSheet("image: url(:/dice/d2rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D3
    def d3click(self):
        dados.append("d3")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D3 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D3 ")

    def d3press(self):
        self.botaoD3.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 13px;\n"
"image: url(:/dice/d3cyan.png);")

    def d3release(self):
        self.botaoD3.setStyleSheet("image: url(:/dice/d3rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 10px;\n"
"")

    #D4
    def d4click(self):
        dados.append("d4")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D4 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D4 ")

    def d4press(self):
        self.botaoD4.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"

"image: url(:/dice/d4cyan.png);")
    def d4release(self):
        self.botaoD4.setStyleSheet("image: url(:/dice/d4rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D6
    def d6click(self):
        dados.append("d6")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D6 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D6 ")

    def d6press(self):
        self.botaoD6.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d6cyan.png);")

    def d6release(self):
        self.botaoD6.setStyleSheet("image: url(:/dice/d6rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D8
    def d8click(self):
        dados.append("d8")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D8 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D8 ")

    def d8press(self):
        self.botaoD8.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d8cyan.png);")
    def d8release(self):
        self.botaoD8.setStyleSheet("image: url(:/dice/d8rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D10
    def d10click(self):
        dados.append("d10")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D10 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D10 ")

    def d10press(self):
        self.botaoD10.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d10cyan.png);")
    def d10release(self):
        self.botaoD10.setStyleSheet("image: url(:/dice/d10rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D12
    def d12click(self):
        dados.append("d12")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D12 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D12 ")

    def d12press(self):
        self.botaoD12.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d12cyan.png);")
    def d12release(self):
        self.botaoD12.setStyleSheet("image: url(:/dice/d12rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D20
    def d20click(self):
        dados.append("d20")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D20 ")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D20 ")

    def d20press(self):
        self.botaoD20.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d20cyan.png);")

    def d20release(self):
        self.botaoD20.setStyleSheet("image: url(:/dice/d20rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D100 decimal
    def d100Dclick(self):
        dados.append("d100d")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice: D100d")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D100d ")

    def d100Dpress(self):
        self.botaoD100.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d100dcyan.png);")

    def d100Drelease(self):
        self.botaoD100.setStyleSheet("image: url(:/dice/d100drosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

    #D100 decimal
    def d100Aclick(self):
        dados.append("d100a")
        if len(self.labelFormula.text()) > 70 or self.labelFormula.text() == demais:
             self.labelFormula.setText(demais)
        elif self.labelFormula.text() == "Dice: ":
             self.labelFormula.setText("Dice:  D100a")
        else:
             bruh = self.labelFormula.text()
             self.labelFormula.setText(bruh + "+ D100a ")

    def d100Apress(self):
        self.botaoD100_2.setStyleSheet(
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: inset;\n"
"padding: 5px;\n"
"image: url(:/dice/d100cyan.png);")

    def d100Arelease(self):
        self.botaoD100_2.setStyleSheet("image: url(:/dice/d100rosa.png);\n"
"\n"
"border-top-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.517, stop:0 rgba(0, 221, 221, 255), stop:1 rgba(255, 0, 255, 255));\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"padding: 2px;\n"
"")

#------------------ INICIAR PROGRAMA ---------------------#
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaDados = QtWidgets.QMainWindow()
    ui = Ui_janelaDados()
    ui.setupUi(janelaDados)
    janelaDados.show()
    sys.exit(app.exec_())