# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sobrejanela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SOBREJanela(object):
    def setupUi(self, SOBREJanela):
        SOBREJanela.setObjectName("SOBREJanela")
        SOBREJanela.resize(600, 340)
        SOBREJanela.setMaximumSize(QtCore.QSize(600, 340))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/sobre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SOBREJanela.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SOBREJanela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.framebottom = QtWidgets.QFrame(self.centralwidget)
        self.framebottom.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.272727 rgba(230, 89, 60, 255), stop:0.642045 rgba(255, 59, 59, 255));")
        self.framebottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebottom.setObjectName("framebottom")
        self.frametop = QtWidgets.QFrame(self.framebottom)
        self.frametop.setGeometry(QtCore.QRect(-2, -30, 604, 91))
        self.frametop.setMaximumSize(QtCore.QSize(604, 91))
        self.frametop.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frametop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frametop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametop.setObjectName("frametop")
        self.logoyt = QtWidgets.QLabel(self.frametop)
        self.logoyt.setGeometry(QtCore.QRect(345, 34, 81, 51))
        self.logoyt.setText("")
        self.logoyt.setPixmap(QtGui.QPixmap("imagens/logoyt.png"))
        self.logoyt.setScaledContents(True)
        self.logoyt.setObjectName("logoyt")
        self.downtube = QtWidgets.QLabel(self.frametop)
        self.downtube.setGeometry(QtCore.QRect(416, 31, 181, 61))
        self.downtube.setText("")
        self.downtube.setPixmap(QtGui.QPixmap("imagens/downtubelogo.png"))
        self.downtube.setScaledContents(True)
        self.downtube.setObjectName("downtube")
        self.iflogo = QtWidgets.QLabel(self.frametop)
        self.iflogo.setGeometry(QtCore.QRect(31, 39, 161, 41))
        self.iflogo.setText("")
        self.iflogo.setPixmap(QtGui.QPixmap("imagens/iflogoo.png"))
        self.iflogo.setScaledContents(True)
        self.iflogo.setObjectName("iflogo")
        self.IniTEXTO = QtWidgets.QLabel(self.framebottom)
        self.IniTEXTO.setGeometry(QtCore.QRect(8, 70, 321, 81))
        self.IniTEXTO.setStyleSheet("font: 10pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: white;")
        self.IniTEXTO.setObjectName("IniTEXTO")
        self.CriadoresT = QtWidgets.QLabel(self.framebottom)
        self.CriadoresT.setGeometry(QtCore.QRect(10, 160, 121, 171))
        self.CriadoresT.setStyleSheet("font: 10pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: white;")
        self.CriadoresT.setObjectName("CriadoresT")
        self.TutoTEXTO = QtWidgets.QLabel(self.framebottom)
        self.TutoTEXTO.setGeometry(QtCore.QRect(138, 160, 191, 171))
        self.TutoTEXTO.setStyleSheet("font: 10pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: white;")
        self.TutoTEXTO.setObjectName("TutoTEXTO")
        self.BrincaTEXTO = QtWidgets.QLabel(self.framebottom)
        self.BrincaTEXTO.setGeometry(QtCore.QRect(390, 70, 201, 81))
        self.BrincaTEXTO.setStyleSheet("font: 10pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: white;")
        self.BrincaTEXTO.setObjectName("BrincaTEXTO")
        self.SimB1 = QtWidgets.QPushButton(self.framebottom)
        self.SimB1.setGeometry(QtCore.QRect(390, 160, 75, 23))
        self.SimB1.setStyleSheet("QPushButton{\n"
"font: 8pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: white;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 8pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: grey;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.SimB1.setObjectName("SimB1")
        self.SimB2 = QtWidgets.QPushButton(self.framebottom)
        self.SimB2.setGeometry(QtCore.QRect(516, 160, 75, 23))
        self.SimB2.setStyleSheet("QPushButton{\n"
"font: 8pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: white;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 8pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: grey;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.SimB2.setObjectName("SimB2")
        self.BrincaTEXTO_2 = QtWidgets.QLabel(self.framebottom)
        self.BrincaTEXTO_2.setGeometry(QtCore.QRect(390, 220, 201, 81))
        self.BrincaTEXTO_2.setStyleSheet("font: 10pt \"Gobold Thin Light\";\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"border-color: white;")
        self.BrincaTEXTO_2.setObjectName("BrincaTEXTO_2")
        self.verticalLayout.addWidget(self.framebottom)
        SOBREJanela.setCentralWidget(self.centralwidget)

        self.retranslateUi(SOBREJanela)
        self.SimB1.clicked.connect(SOBREJanela.close)
        self.SimB2.clicked.connect(SOBREJanela.close)
        QtCore.QMetaObject.connectSlotsByName(SOBREJanela)

    def retranslateUi(self, SOBREJanela):
        _translate = QtCore.QCoreApplication.translate
        SOBREJanela.setWindowTitle(_translate("SOBREJanela", "Sobre nós - DownTUBE"))
        self.IniTEXTO.setText(_translate("SOBREJanela", "<html><head/><body><p><span style=\" font-size:9pt; color:#ffffff;\">Projeto final idealizado para a disciplina de programação</span></p><p><span style=\" font-size:9pt; color:#ffffff;\">orientada e estruturada a objetos.</span></p><p><span style=\" font-size:9pt; color:#ffffff;\">Sob orientação do prof. Clayton maciel.</span></p><p><br/></p></body></html>"))
        self.CriadoresT.setText(_translate("SOBREJanela", "<html><head/><body><p><span style=\" color:#ffffff;\">Idealizadores:</span></p><p><span style=\" color:#ffffff;\">ana clara</span></p><p><span style=\" color:#ffffff;\">ruan victor</span></p><p><span style=\" color:#ffffff;\">maria eduarda</span></p><p><span style=\" color:#ffffff;\">felipe rezes</span></p><p><span style=\" color:#ffffff;\">yan lucas</span></p></body></html>"))
        self.TutoTEXTO.setText(_translate("SOBREJanela", "<html><head/><body><p><span style=\" color:#ffffff;\">Como utilizar o programa:</span></p><p><span style=\" color:#ffffff;\">1.copie o link desejado do youtube;</span></p><p><span style=\" color:#ffffff;\">2. cole o link no campo indicado;</span></p><p><span style=\" color:#ffffff;\">3. escolha a opção para baixar</span></p><p><span style=\" color:#ffffff;\">em mp3 ou mp4;</span></p><p><span style=\" color:#ffffff;\">4. esperar o download finalizar.</span></p><p><span style=\" color:#ffffff;\"><br/></span></p><p><span style=\" color:#ffffff;\"><br/></span></p></body></html>"))
        self.BrincaTEXTO.setText(_translate("SOBREJanela", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Atenção!</span></p><p align=\"center\"><span style=\" color:#ffffff;\">Já atribuiu nota máxima ao projeto?</span></p></body></html>"))
        self.SimB1.setText(_translate("SOBREJanela", "Sim"))
        self.SimB2.setText(_translate("SOBREJanela", "Sim"))
        self.BrincaTEXTO_2.setText(_translate("SOBREJanela", "<html><head/><body><p><span style=\" color:#ffffff;\">o arquivo estará disponível na pasta</span></p><p><span style=\" color:#ffffff;\">downloads (criada dentro do próprio </span></p><p><span style=\" color:#ffffff;\">python).</span></p></body></html>"))
