# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\elnat\Documents\Nuvem\Code_python\Projeto_final\Sobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sobre(object):
    def setupUi(self, Sobre):
        Sobre.setObjectName("Sobre")
        Sobre.resize(331, 395)
        Sobre.setMinimumSize(QtCore.QSize(331, 395))
        Sobre.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(Sobre)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frame)
        Sobre.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sobre)
        QtCore.QMetaObject.connectSlotsByName(Sobre)

    def retranslateUi(self, Sobre):
        _translate = QtCore.QCoreApplication.translate
        Sobre.setWindowTitle(_translate("Sobre", "Sobre"))
        self.label.setText(_translate("Sobre", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Sobre</span></p></body></html>"))
        self.label_2.setText(_translate("Sobre", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Componentes do grupo:<br/>Ana Caroliny Virgilo de Medeiros<br/>Eber Selemuel das Chagas<br/>Élnatan da Silva Honorato<br/>Isabela Vitória Azevedo Pimentel<br/><br/>Professor:<br/>Clayton Maciel Costa</span></p></body></html>"))