# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segundatelaimc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_info(object):
    def setupUi(self, tela_info):
        tela_info.setObjectName("tela_info")
        tela_info.resize(346, 415)
        tela_info.setMaximumSize(QtCore.QSize(346, 415))
        tela_info.setStyleSheet("background-color: rgb(42, 93, 156);")
        self.centralwidget = QtWidgets.QWidget(tela_info)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ent_peso = QtWidgets.QLineEdit(self.centralwidget)
        self.ent_peso.setGeometry(QtCore.QRect(170, 130, 121, 21))
        self.ent_peso.setObjectName("ent_peso")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 130, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 141, 16))
        self.label_3.setObjectName("label_3")
        self.ent_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.ent_altura.setGeometry(QtCore.QRect(170, 220, 121, 20))
        self.ent_altura.setObjectName("ent_altura")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 220, 47, 20))
        self.label_4.setObjectName("label_4")
        self.botao_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.botao_calcular.setGeometry(QtCore.QRect(130, 300, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_calcular.setFont(font)
        self.botao_calcular.setStyleSheet("background-color: rgb(135, 193, 213);")
        self.botao_calcular.setObjectName("botao_calcular")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.grafico = QtWidgets.QLabel(self.centralwidget)
        self.grafico.setGeometry(QtCore.QRect(-40, 270, 161, 201))
        self.grafico.setText("")
        self.grafico.setPixmap(QtGui.QPixmap("grafico.png"))
        self.grafico.setScaledContents(True)
        self.grafico.setObjectName("grafico")
        tela_info.setCentralWidget(self.centralwidget)
        self.botao_calcular.clicked.connect(self.abrirResultado)
        self.retranslateUi(tela_info)
        QtCore.QMetaObject.connectSlotsByName(tela_info)

    def abrirResultado(self):
        from telaresultado import Ui_tela_resultado
        self.janela = QtWidgets.QMainWindow()
        self.tela = Ui_tela_resultado()
        self.tela.setupUi(self.janela, self)
        self.janela.show()

    def getImc(self):
        peso = float(self.ent_peso.text())
        altura = float(self.ent_altura.text())
        return round((peso / (altura * altura)), 2)

    def retranslateUi(self, tela_info):
        _translate = QtCore.QCoreApplication.translate
        tela_info.setWindowTitle(_translate("tela_info", "Calculadora de IMC"))
        self.label.setText(_translate("tela_info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff; vertical-align:super;\">Insira o seu peso:</span></p></body></html>"))
        self.label_2.setText(_translate("tela_info", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">(Kg)</span></p></body></html>"))
        self.label_3.setText(_translate("tela_info", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Insira sua altura:</span></p></body></html>"))
        self.label_4.setText(_translate("tela_info", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">(m)</span></p></body></html>"))
        self.botao_calcular.setText(_translate("tela_info", "Calcular"))
        self.label_5.setText(_translate("tela_info", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Índice de Massa Corporal</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_info = QtWidgets.QMainWindow()
    ui = Ui_tela_info()
    ui.setupUi(tela_info)
    tela_info.show()
    sys.exit(app.exec_())
