# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telasobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telasobre(object):
    def setupUi(self, telasobre):
        telasobre.setObjectName("telasobre")
        telasobre.resize(316, 239)
        telasobre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(telasobre)
        self.centralwidget.setObjectName("centralwidget")
        self.feitopor = QtWidgets.QLabel(self.centralwidget)
        self.feitopor.setGeometry(QtCore.QRect(20, 120, 271, 71))
        self.feitopor.setStyleSheet("font: 63 8pt \"Open Sans SemiBold\";")
        self.feitopor.setObjectName("feitopor")
        self.fotoif = QtWidgets.QLabel(self.centralwidget)
        self.fotoif.setGeometry(QtCore.QRect(50, 10, 201, 91))
        self.fotoif.setText("")
        self.fotoif.setPixmap(QtGui.QPixmap("logoifrn.bmp"))
        self.fotoif.setScaledContents(True)
        self.fotoif.setObjectName("fotoif")
        self.botaovoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaovoltar.setGeometry(QtCore.QRect(115, 200, 75, 23))
        self.botaovoltar.clicked.connect(telasobre.close)
        self.botaovoltar.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.botaovoltar.setObjectName("botaovoltar")
        telasobre.setCentralWidget(self.centralwidget)

        self.retranslateUi(telasobre)
        QtCore.QMetaObject.connectSlotsByName(telasobre)

    def retranslateUi(self, telasobre):
        _translate = QtCore.QCoreApplication.translate
        telasobre.setWindowTitle(_translate("telasobre", "Sobre "))
        self.feitopor.setText(_translate("telasobre", "<html><head/><body><p align=\"center\">Desenvolvido por Aretuza Raquely, Clara Manuella, </p><p align=\"center\">Stefany Gabrielle e Viviany Barros</p><p align=\"center\">Versão 1.0</p></body></html>"))
        self.botaovoltar.setText(_translate("telasobre", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telasobre = QtWidgets.QMainWindow()
    ui = Ui_telasobre()
    ui.setupUi(telasobre)
    telasobre.show()
    sys.exit(app.exec_())
