# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaResultado.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_resultado(object):
    def setupUi(self, tela_resultado, parent_obj=None):
        self.parent_obj = parent_obj
        tela_resultado.setObjectName("tela_resultado")
        tela_resultado.resize(346, 415)
        tela_resultado.setStyleSheet("background-color: rgb(42, 93, 156);")
        self.centralwidget = QtWidgets.QWidget(tela_resultado)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 110, 111, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.valor_imc = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_imc.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.valor_imc.setObjectName("valor_imc")
        self.considerado = QtWidgets.QLineEdit(self.centralwidget)
        self.considerado.setGeometry(QtCore.QRect(160, 190, 113, 20))
        self.considerado.setObjectName("considerado")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 270, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grafico = QtWidgets.QLabel(self.centralwidget)
        self.grafico.setGeometry(QtCore.QRect(-40, 270, 161, 201))
        self.grafico.setText("")
        self.grafico.setPixmap(QtGui.QPixmap("grafico.png"))
        self.grafico.setScaledContents(True)
        self.grafico.setObjectName("grafico")
        self.btao_voltar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btao_voltar.setStyleSheet("background-color: rgb(135, 193, 213);")
        self.btao_voltar.setObjectName("btao_voltar")
        self.btao_voltar.clicked.connect(tela_resultado.close)
        self.verticalLayout.addWidget(self.btao_voltar)
        self.tabela_online = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tabela_online.setStyleSheet("background-color: rgb(135, 193, 213);")
        self.tabela_online.setObjectName("tabela_online")
        self.tabela_online.clicked.connect(self.abrir_navegador)
        self.verticalLayout.addWidget(self.tabela_online)
        tela_resultado.setCentralWidget(self.centralwidget)


        if self.parent_obj:
            imc = self.parent_obj.getImc()
            self.valor_imc.setText(str(imc))
            if imc <= 18.5:
                self.considerado.setText("abaixo do peso")

            elif 18.6 <= imc <= 24.9:
                self.considerado.setText("Peso Ideal")

            elif 25 <= imc <=29.9:
                sel.considerado.setText("Levemente acima do peso")

            elif 30 <= imc <= 34.9:
                self.considerado.setText("Obesidade grau I")

            elif 35 <= imc <= 39.9:
                self.considerado.setText("Obesidade grau II (severa)")

            elif imc >= 40:
                self.considerado.setText(("Obesidade grau III (mórbida"))


        self.retranslateUi(tela_resultado)
        QtCore.QMetaObject.connectSlotsByName(tela_resultado)

    def abrir_navegador(self):
        import webbrowser
        webbrowser.open('https://www.youtube.com/watch?v=w6lqLoSOcLI')


    def retranslateUi(self, tela_resultado):
        _translate = QtCore.QCoreApplication.translate
        tela_resultado.setWindowTitle(_translate("tela_resultado", "Calculadora de IMC"))
        self.label.setText(_translate("tela_resultado", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Valor do IMC </span></p></body></html>"))
        self.label_2.setText(_translate("tela_resultado", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Considerado</span></p></body></html>"))
        self.label_3.setText(_translate("tela_resultado", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">RESULTADO</span></p></body></html>"))
        self.btao_voltar.setText(_translate("tela_resultado", "Voltar"))
        self.tabela_online.setText(_translate("tela_resultado", "  Dicas para saúde on-line"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_resultado = QtWidgets.QMainWindow()
    ui = Ui_tela_resultado()
    ui.setupUi(tela_resultado)
    tela_resultado.show()
    sys.exit(app.exec_())
