# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telainicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_inicial(object):
    def setupUi(self, tela_inicial):
        tela_inicial.setObjectName("tela_inicial")
        tela_inicial.resize(346, 415)
        self.widget = QtWidgets.QWidget(tela_inicial)
        self.widget.setMinimumSize(QtCore.QSize(346, 41))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 270, 141, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutvertical = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutvertical.setContentsMargins(0, 0, 0, 0)
        self.layoutvertical.setObjectName("layoutvertical")
        self.calcularimc = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calcularimc.setStyleSheet("background-color: rgb(135, 193, 213);")
        self.calcularimc.setObjectName("calcularimc")
        self.layoutvertical.addWidget(self.calcularimc)
        self.calcularimc.clicked.connect(self.abrir_calculadora)
        self.sobre = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sobre.setStyleSheet("background-color: rgb(135, 193, 213);")
        self.sobre.setObjectName("sobre")
        self.layoutvertical.addWidget(self.sobre)
        self.sobre.clicked.connect(self.abrir_sobre)
        self.foto = QtWidgets.QLabel(self.widget)
        self.foto.setGeometry(QtCore.QRect(0, 0, 351, 421))
        self.foto.setText("")
        self.foto.setPixmap(QtGui.QPixmap("MicrosoftTeams-image.png"))
        self.foto.setScaledContents(True)
        self.foto.setObjectName("foto")
        self.foto.raise_()
        self.verticalLayoutWidget.raise_()
        tela_inicial.setCentralWidget(self.widget)

        self.retranslateUi(tela_inicial)
        QtCore.QMetaObject.connectSlotsByName(tela_inicial)
    def abrir_calculadora(self):
        from segundatelaimc import Ui_tela_info
        self.aba = QtWidgets.QMainWindow()
        self.calcular = Ui_tela_info()
        self.calcular.setupUi(self.aba)
        self.aba.show()

    def abrir_sobre(self):
        from telasobre import Ui_telasobre
        self.janela = QtWidgets.QMainWindow()
        self.sobre = Ui_telasobre()
        self.sobre.setupUi(self.janela)
        self.janela.show()

    def retranslateUi(self, tela_inicial):
        _translate = QtCore.QCoreApplication.translate
        tela_inicial.setWindowTitle(_translate("tela_inicial", "Calculadora IMC - v.1.0"))
        self.calcularimc.setText(_translate("tela_inicial", "Calcular IMC"))
        self.sobre.setText(_translate("tela_inicial", "Sobre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_inicial = QtWidgets.QMainWindow()
    ui = Ui_tela_inicial()
    ui.setupUi(tela_inicial)
    tela_inicial.show()
    sys.exit(app.exec_())
