# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acai4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 580))
        self.label.setMinimumSize(QtCore.QSize(391, 580))
        self.label.setMaximumSize(QtCore.QSize(391, 580))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 25, 50))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 25, 50))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 25, 50))
        self.label_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 0, 25, 50))
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 25, 50))
        self.label_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 0, 25, 50))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 0, 25, 50))
        self.label_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 0, 25, 50))
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 25, 50))
        self.label_10.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 0, 25, 50))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-5, 20, 461, 561))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\Fundo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_14.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 150, 161, 21))
        self.label_16.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 180, 221, 41))
        self.label_17.setStyleSheet("color: rgb(247, 89, 113);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(180, 260, 51, 21))
        self.label_18.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.banana = QtWidgets.QCheckBox(self.centralwidget)
        self.banana.setGeometry(QtCore.QRect(160, 320, 21, 21))
        self.banana.setStyleSheet("")
        self.banana.setText("")
        self.banana.setCheckable(True)
        self.banana.setChecked(False)
        self.banana.setAutoRepeat(False)
        self.banana.setAutoExclusive(False)
        self.banana.setObjectName("banana")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(180, 320, 51, 21))
        self.label_19.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_19.setObjectName("label_19")
        self.granola = QtWidgets.QCheckBox(self.centralwidget)
        self.granola.setGeometry(QtCore.QRect(160, 350, 21, 21))
        self.granola.setStyleSheet("")
        self.granola.setText("")
        self.granola.setCheckable(True)
        self.granola.setChecked(False)
        self.granola.setAutoRepeat(False)
        self.granola.setAutoExclusive(False)
        self.granola.setObjectName("granola")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(180, 230, 51, 21))
        self.label_20.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(30, 260, 101, 21))
        self.label_21.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_21.setObjectName("label_21")
        self.kit_kat = QtWidgets.QCheckBox(self.centralwidget)
        self.kit_kat.setGeometry(QtCore.QRect(160, 260, 21, 21))
        self.kit_kat.setStyleSheet("")
        self.kit_kat.setText("")
        self.kit_kat.setCheckable(True)
        self.kit_kat.setChecked(False)
        self.kit_kat.setAutoRepeat(False)
        self.kit_kat.setAutoExclusive(False)
        self.kit_kat.setObjectName("kit_kat")
        self.nutella = QtWidgets.QCheckBox(self.centralwidget)
        self.nutella.setGeometry(QtCore.QRect(160, 290, 21, 21))
        self.nutella.setStyleSheet("")
        self.nutella.setText("")
        self.nutella.setCheckable(True)
        self.nutella.setChecked(False)
        self.nutella.setAutoRepeat(False)
        self.nutella.setAutoExclusive(False)
        self.nutella.setObjectName("nutella")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(30, 230, 101, 21))
        self.label_22.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_22.setObjectName("label_22")
        self.ouro_branco = QtWidgets.QCheckBox(self.centralwidget)
        self.ouro_branco.setGeometry(QtCore.QRect(10, 380, 21, 21))
        self.ouro_branco.setStyleSheet("")
        self.ouro_branco.setText("")
        self.ouro_branco.setCheckable(True)
        self.ouro_branco.setChecked(False)
        self.ouro_branco.setAutoRepeat(False)
        self.ouro_branco.setAutoExclusive(False)
        self.ouro_branco.setObjectName("ouro_branco")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(30, 350, 101, 21))
        self.label_23.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(180, 290, 51, 21))
        self.label_24.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_24.setObjectName("label_24")
        self.fini = QtWidgets.QCheckBox(self.centralwidget)
        self.fini.setGeometry(QtCore.QRect(160, 230, 21, 21))
        self.fini.setStyleSheet("")
        self.fini.setText("")
        self.fini.setCheckable(True)
        self.fini.setChecked(False)
        self.fini.setAutoRepeat(False)
        self.fini.setAutoExclusive(False)
        self.fini.setObjectName("fini")
        self.chocolate = QtWidgets.QCheckBox(self.centralwidget)
        self.chocolate.setGeometry(QtCore.QRect(10, 230, 21, 21))
        self.chocolate.setStyleSheet("")
        self.chocolate.setText("")
        self.chocolate.setCheckable(True)
        self.chocolate.setChecked(False)
        self.chocolate.setAutoRepeat(False)
        self.chocolate.setAutoExclusive(False)
        self.chocolate.setObjectName("chocolate")
        self.leite_po = QtWidgets.QCheckBox(self.centralwidget)
        self.leite_po.setGeometry(QtCore.QRect(10, 320, 21, 21))
        self.leite_po.setStyleSheet("")
        self.leite_po.setText("")
        self.leite_po.setCheckable(True)
        self.leite_po.setChecked(False)
        self.leite_po.setAutoRepeat(False)
        self.leite_po.setAutoExclusive(False)
        self.leite_po.setObjectName("leite_po")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(30, 320, 101, 21))
        self.label_27.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(30, 290, 101, 21))
        self.label_28.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_28.setObjectName("label_28")
        self.coco_rola = QtWidgets.QCheckBox(self.centralwidget)
        self.coco_rola.setGeometry(QtCore.QRect(10, 350, 21, 21))
        self.coco_rola.setStyleSheet("")
        self.coco_rola.setText("")
        self.coco_rola.setCheckable(True)
        self.coco_rola.setChecked(False)
        self.coco_rola.setAutoRepeat(False)
        self.coco_rola.setAutoExclusive(False)
        self.coco_rola.setObjectName("coco_rola")
        self.oreo = QtWidgets.QCheckBox(self.centralwidget)
        self.oreo.setGeometry(QtCore.QRect(160, 380, 21, 21))
        self.oreo.setStyleSheet("")
        self.oreo.setText("")
        self.oreo.setCheckable(True)
        self.oreo.setChecked(False)
        self.oreo.setAutoRepeat(False)
        self.oreo.setAutoExclusive(False)
        self.oreo.setObjectName("oreo")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(30, 380, 101, 21))
        self.label_30.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_30.setObjectName("label_30")
        self.choco_leite = QtWidgets.QCheckBox(self.centralwidget)
        self.choco_leite.setGeometry(QtCore.QRect(10, 260, 21, 21))
        self.choco_leite.setStyleSheet("")
        self.choco_leite.setText("")
        self.choco_leite.setCheckable(True)
        self.choco_leite.setChecked(False)
        self.choco_leite.setAutoRepeat(False)
        self.choco_leite.setAutoExclusive(False)
        self.choco_leite.setObjectName("choco_leite")
        self.leite_conde = QtWidgets.QCheckBox(self.centralwidget)
        self.leite_conde.setGeometry(QtCore.QRect(10, 290, 21, 21))
        self.leite_conde.setStyleSheet("")
        self.leite_conde.setText("")
        self.leite_conde.setCheckable(True)
        self.leite_conde.setChecked(False)
        self.leite_conde.setAutoRepeat(False)
        self.leite_conde.setAutoExclusive(False)
        self.leite_conde.setObjectName("leite_conde")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(260, 220, 121, 111))
        self.label_31.setStyleSheet("")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaAcai\Acai.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.finalizar = QtWidgets.QPushButton(self.centralwidget)
        self.finalizar.setGeometry(QtCore.QRect(260, 400, 101, 41))
        self.finalizar.setStyleSheet("QPushButton {\n"
"    color: rgb(247, 89, 113);\n"
"    font: 15pt \"Bukhari Script\";\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.finalizar.setObjectName("finalizar")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(145, 520, 101, 41))
        self.label_32.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 28pt \"Bukhari Script\";")
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(180, 380, 51, 21))
        self.label_34.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(180, 350, 51, 21))
        self.label_35.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(33, 470, 111, 131))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaAcai\Acaizinho.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(240, 470, 111, 131))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaAcai\Acaizinho.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(350, 60, 31, 31))
        self.voltar.setAutoFillBackground(False)
        self.voltar.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voltar.setIcon(icon)
        self.voltar.setIconSize(QtCore.QSize(20, 25))
        self.voltar.setObjectName("voltar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 16, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tamanhos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tamanhos.setContentsMargins(0, 0, 0, 0)
        self.tamanhos.setObjectName("tamanhos")
        self.ml_250 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_250.setStyleSheet("")
        self.ml_250.setText("")
        self.ml_250.setObjectName("ml_250")
        self.ml_250.clicked.connect(self.ml_Func)
        self.tamanhos.addWidget(self.ml_250)
        self.ml_500 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_500.setStyleSheet("")
        self.ml_500.setText("")
        self.ml_500.setObjectName("ml_500")
        self.ml_500.clicked.connect(self.ml_Func)
        self.tamanhos.addWidget(self.ml_500)
        self.ml_750 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_750.setStyleSheet("")
        self.ml_750.setText("")
        self.ml_750.clicked.connect(self.ml_Func)
        self.ml_750.setObjectName("ml_750")
        self.tamanhos.addWidget(self.ml_750)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(30, 126, 101, 21))
        self.label_29.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_29.setObjectName("label_29")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(30, 100, 101, 21))
        self.label_33.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(30, 74, 101, 21))
        self.label_36.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")

        self.pedido = QtWidgets.QLabel(self.centralwidget)
        self.pedido.setGeometry(QtCore.QRect(20, 410, 230, 31))
        self.pedido.setObjectName("pedido")
        self.pedido.setStyleSheet("\n"
                                  "QLabel {\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "border: 4px solid rgb(85, 255, 255);\n"
                                  "color: rgb(247, 89, 113);\n"
                                  "}\n"
                                  "")

        self.label_36.setObjectName("label_36")
        MainWindow.setCentralWidget(self.centralwidget)

        self.finalizar.setDisabled(True)

        self.ml_250.clicked.connect(self.hab_finaliza)
        self.ml_500.clicked.connect(self.hab_finaliza)
        self.ml_750.clicked.connect(self.hab_finaliza)

        self.voltar.clicked.connect(self.volta)
        self.voltar.clicked.connect(MainWindow.hide)

        self.finalizar.clicked.connect(self.finaliza)
        self.finalizar.clicked.connect(MainWindow.hide)

        self.chocolate.clicked.connect(self.complemento)
        self.choco_leite.clicked.connect(self.complemento)
        self.leite_conde.clicked.connect(self.complemento)
        self.leite_po.clicked.connect(self.complemento)
        self.coco_rola.clicked.connect(self.complemento)
        self.ouro_branco.clicked.connect(self.complemento)
        self.fini.clicked.connect(self.complemento)
        self.kit_kat.clicked.connect(self.complemento)
        self.nutella.clicked.connect(self.complemento)
        self.banana.clicked.connect(self.complemento)
        self.granola.clicked.connect(self.complemento)
        self.oreo.clicked.connect(self.complemento)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setFixedWidth(385)
        MainWindow.setFixedHeight(580)

    def ml_Func(self):
        if self.ml_250.isChecked():
            self.pedido.setText(f'Pedido - Açai Pequeno 200ml R$ 12,00')
        if self.ml_500.isChecked():
            self.pedido.setText(f'Pedido - Açai Médio 500ml R$ 18,00')
        if self.ml_750.isChecked():
            self.pedido.setText(f'Pedido - Açai Grande 750ml R$ 24,00')

    def hab_finaliza(self):
        self.finalizar.setDisabled(False)
    def volta(self):
        from comprar import Ui_Comprar
        self.janela = QtWidgets.QMainWindow()
        self.comprar = Ui_Comprar()
        self.comprar.setupUi(self.janela)
        self.janela.show()
    def finaliza(self):
        from pagamento import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.pagamento = Ui_MainWindow()
        self.pagamento.setupUi(self.janela)
        self.janela.show()
    def complemento(self):
        quant = 0
        if self.chocolate.isChecked():
            quant += 1
        if self.choco_leite.isChecked():
            quant += 1
        if self.leite_conde.isChecked():
            quant += 1
        if self.leite_po.isChecked():
            quant += 1
        if self.coco_rola.isChecked():
            quant += 1
        if self.ouro_branco.isChecked():
            quant += 1
        if self.fini.isChecked():
            quant += 1
        if self.kit_kat.isChecked():
            quant += 1
        if self.nutella.isChecked():
            quant += 1
        if self.banana.isChecked():
            quant += 1
        if self.granola.isChecked():
            quant += 1
        if self.oreo.isChecked():
            quant += 1
        if quant == 7:
            if self.chocolate.isChecked() == False:
                self.chocolate.setDisabled(True)
            if self.choco_leite.isChecked() == False:
                self.choco_leite.setDisabled(True)
            if self.leite_conde.isChecked() == False:
                self.leite_conde.setDisabled(True)
            if self.leite_po.isChecked() == False:
                self.leite_po.setDisabled(True)
            if self.coco_rola.isChecked() == False:
                self.coco_rola.setDisabled(True)
            if self.ouro_branco.isChecked() == False:
                self.ouro_branco.setDisabled(True)
            if self.fini.isChecked() == False:
                self.fini.setDisabled(True)
            if self.kit_kat.isChecked() == False:
                self.kit_kat.setDisabled(True)
            if self.nutella.isChecked() == False:
                self.nutella.setDisabled(True)
            if self.banana.isChecked() == False:
                self.banana.setDisabled(True)
            if self.granola.isChecked() == False:
                self.granola.setDisabled(True)
            if self.oreo.isChecked() == False:
                self.oreo.setDisabled(True)
        if quant < 7:
            self.chocolate.setDisabled(False)
            self.choco_leite.setDisabled(False)
            self.leite_conde.setDisabled(False)
            self.leite_po.setDisabled(False)
            self.coco_rola.setDisabled(False)
            self.ouro_branco.setDisabled(False)
            self.fini.setDisabled(False)
            self.kit_kat.setDisabled(False)
            self.nutella.setDisabled(False)
            self.banana.setDisabled(False)
            self.granola.setDisabled(False)
            self.oreo.setDisabled(False)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tamanhos:</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Complementos:</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">*Todos os açaís, independentemente do tamanho,</span></p><p><span style=\" font-size:7pt;\">só podem possuir 7 complementos*</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Kit Kat</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Banana</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Fini</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Chocolate ao Leite</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Chocolate 70%</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Coco Ralado</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Nutella</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>Leite em Pó</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>Leite Condensado</p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>Ouro Branco</p></body></html>"))
        self.finalizar.setText(_translate("MainWindow", "Finalizar"))
        self.label_32.setText(_translate("MainWindow", "Açaís"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p>Oreo</p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p>Granola</p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p>750 mL - R$ 24,00</p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p>500 mL - R$ 18,00</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>250 mL - R$ 12,00</p></body></html>"))
        self.pedido.setText(_translate("MainWindow", "Pedido -"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
