# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalizar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        MainWindow.setStyleSheet("font: 8pt \"Open Sans\";")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 580))
        self.label.setMinimumSize(QtCore.QSize(391, 580))
        self.label.setMaximumSize(QtCore.QSize(391, 580))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 35, 580))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 0, 35, 580))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 0, 35, 580))
        self.label_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 0, 35, 580))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 0, 35, 580))
        self.label_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(360, 0, 35, 580))
        self.label_14.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(120, 0, 35, 580))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-5, 0, 401, 581))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\Fundo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(35, 500, 321, 61))
        self.label_6.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Bukhari Script\";")
        self.label_6.setObjectName("label_6")
        self.cartao = QtWidgets.QPushButton(self.centralwidget)
        self.cartao.setGeometry(QtCore.QRect(210, 140, 151, 151))
        self.cartao.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.cartao.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaPagamento\OutroPedido.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartao.setIcon(icon)
        self.cartao.setIconSize(QtCore.QSize(200, 200))
        self.cartao.setObjectName("cartao")
        self.cartao.clicked.connect(self.outropedido)
        self.cartao.clicked.connect(MainWindow.hide)
        self.dinheiro = QtWidgets.QPushButton(self.centralwidget)
        self.dinheiro.setGeometry(QtCore.QRect(30, 140, 151, 151))
        self.dinheiro.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.dinheiro.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaPagamento\Fechar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dinheiro.setIcon(icon1)
        self.dinheiro.setIconSize(QtCore.QSize(200, 200))
        self.dinheiro.setObjectName("dinheiro")
        self.dinheiro.clicked.connect(MainWindow.close)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def outropedido(self):
        from inicio_sobre import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.inicio = Ui_MainWindow()
        self.inicio.setupUi(self.janela)
        self.janela.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">Obrigado e volte sempre!</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
