# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inico_sobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        MainWindow.setSizeIncrement(QtCore.QSize(391, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -10, 391, 580))
        self.label.setMaximumSize(QtCore.QSize(391, 580))
        self.label.setSizeIncrement(QtCore.QSize(391, 580))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaInicial\Logo Sorveteria (3).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-10, 0, 391, 591))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 30, 611))
        self.label_2.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, -10, 30, 611))
        self.label_7.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(120, -10, 30, 611))
        self.label_9.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, -10, 30, 611))
        self.label_11.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(240, -10, 30, 611))
        self.label_13.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(300, -10, 30, 611))
        self.label_15.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(360, 0, 31, 611))
        self.label_17.setStyleSheet("background-color: rgb(115, 230, 227);")
        self.label_17.setObjectName("label_17")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(75, 60, 241, 251))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaInicial\CirculoAmarelo.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, -20, 271, 251))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaInicial\Sorveteria_nome.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(120, 150, 271, 251))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaInicial\Icy_Cream.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(90, 110, 231, 121))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"League Spartan\";")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(110, 150, 221, 101))
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"League Spartan\";")
        self.label_16.setObjectName("label_16")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-5, 30, 401, 571))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\Fundo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 380, 491, 291))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaInicial\Sorvete_Picole.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(150, 80, 91, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaInicial\Sorvetinho.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.sobre = QtWidgets.QPushButton(self.centralwidget)
        self.sobre.setGeometry(QtCore.QRect(0, 500, 81, 81))
        self.sobre.setStyleSheet("QPushButton {\n"
"background-color: rgb(112, 68, 55);\n"
"border-radius: 35px;\n"
"}")
        self.sobre.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSobre\sobre_semfundo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sobre.setIcon(icon)
        self.sobre.setIconSize(QtCore.QSize(80, 80))
        self.sobre.setObjectName("sobre")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5.raise_()
        self.label_17.raise_()
        self.label_15.raise_()
        self.label_7.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.sobre.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.trocadetela)
        self.pushButton.clicked.connect(MainWindow.hide)

        self.sobre.clicked.connect(self.bt_sobre)
        self.sobre.clicked.connect(MainWindow.hide)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setFixedWidth(385)
        MainWindow.setFixedHeight(580)

    def trocadetela(self):
        from comprar import Ui_Comprar
        self.janela = QtWidgets.QMainWindow()
        self.comprar = Ui_Comprar()
        self.comprar.setupUi(self.janela)
        self.janela.show()

    def bt_sobre(self):
        from sobre1 import Ui_MainWindow
        self.aba = QtWidgets.QMainWindow()
        self.sobre1 = Ui_MainWindow()
        self.sobre1.setupUi(self.aba)
        self.aba.show()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "APERTE ENTER"))
        self.label_16.setText(_translate("MainWindow", "PARA COMEÇAR!"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
