# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milkshake4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 580))
        self.label.setMinimumSize(QtCore.QSize(391, 580))
        self.label.setMaximumSize(QtCore.QSize(391, 580))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 25, 50))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 25, 50))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-5, 20, 461, 561))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\Fundo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 160, 191, 21))
        self.label_16.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_16.setObjectName("label_16")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 0, 25, 50))
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 0, 25, 50))
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 25, 50))
        self.label_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 0, 25, 50))
        self.label_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 0, 25, 50))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 25, 50))
        self.label_10.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 50, 121, 21))
        self.label_14.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_14.setObjectName("label_14")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(230, 200, 151, 101))
        self.label_31.setStyleSheet("")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaMilkShake\MilkShake.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.finalizar = QtWidgets.QPushButton(self.centralwidget)
        self.finalizar.setGeometry(QtCore.QRect(260, 400, 101, 41))
        self.finalizar.setStyleSheet("QPushButton {\n"
"    color: rgb(247, 89, 113);\n"
"    font: 15pt \"Bukhari Script\";\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.finalizar.setObjectName("finalizar")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 0, 25, 50))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(90, 520, 211, 41))
        self.label_32.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 28pt \"Bukhari Script\";")
        self.label_32.setObjectName("label_32")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 310, 141, 21))
        self.label_26.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_26.setObjectName("label_26")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 25, 50))
        self.label_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(285, 460, 111, 131))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaMilkShake\Shakezinho.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(-5, 460, 111, 131))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaMilkShake\Shakezinho.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(350, 60, 31, 31))
        self.voltar.setAutoFillBackground(False)
        self.voltar.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voltar.setIcon(icon)
        self.voltar.setIconSize(QtCore.QSize(20, 25))
        self.voltar.setObjectName("voltar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 16, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tamanhos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tamanhos.setContentsMargins(0, 0, 0, 0)
        self.tamanhos.setObjectName("tamanhos")

        self.ml_200 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_200.setStyleSheet("font: 8pt \"Open Sans\";")
        self.ml_200.setText("")
        self.ml_200.setObjectName("ml_200")
        self.ml_200.clicked.connect(self.ml_200_Func)

        self.tamanhos.addWidget(self.ml_200)

        self.ml_500 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_500.setStyleSheet("font: 8pt \"Open Sans\";")
        self.ml_500.setText("")
        self.ml_500.setObjectName("ml_500")
        self.ml_500.clicked.connect(self.ml_500_Func)
        self.tamanhos.addWidget(self.ml_500)

        self.ml_700 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_700.setStyleSheet("font: 8pt \"Open Sans\";")
        self.ml_700.setText("")
        self.ml_700.setObjectName("ml_700")
        self.ml_700.clicked.connect(self.ml_700_Func)
        self.tamanhos.addWidget(self.ml_700)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 190, 16, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sabores = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.sabores.setContentsMargins(0, 0, 0, 0)
        self.sabores.setObjectName("sabores")

        self.chocolate = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.chocolate.setStyleSheet("font: 8pt \"Open Sans\";")
        self.chocolate.setText("")
        self.chocolate.setObjectName("chocolate")
        self.chocolate.clicked.connect(self.chocolateFunc)
        self.sabores.addWidget(self.chocolate)

        self.morango = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.morango.setStyleSheet("font: 8pt \"Open Sans\";")
        self.morango.setText("")
        self.morango.setObjectName("morango")
        self.morango.clicked.connect(self.selecionado)
        self.sabores.addWidget(self.morango)

        self.baunilha = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.baunilha.setStyleSheet("font: 8pt \"Open Sans\";")
        self.baunilha.setText("")
        self.baunilha.setObjectName("baunilha")
        self.baunilha.clicked.connect(self.baunilhaFunc)
        self.sabores.addWidget(self.baunilha)

        self.nutella = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.nutella.setStyleSheet("font: 8pt \"Open Sans\";")
        self.nutella.setText("")
        self.nutella.setObjectName("nutella")
        self.nutella.clicked.connect(self.nutellaFunc)
        self.sabores.addWidget(self.nutella)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 340, 16, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.complementos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.complementos.setContentsMargins(0, 0, 0, 0)
        self.complementos.setObjectName("complementos")

        self.ovo_oreo = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.ovo_oreo.setStyleSheet("font: 8pt \"Open Sans\";")
        self.ovo_oreo.setText("")
        self.ovo_oreo.setObjectName("ovo_oreo")
        self.complementos.addWidget(self.ovo_oreo)

        self.chanti_cereja = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.chanti_cereja.setStyleSheet("font: 8pt \"Open Sans\";")
        self.chanti_cereja.setText("")
        self.chanti_cereja.setObjectName("chanti_cereja")
        self.complementos.addWidget(self.chanti_cereja)

        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(50, 73, 101, 21))
        self.label_36.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(50, 196, 61, 21))
        self.label_37.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(50, 126, 101, 21))
        self.label_38.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(50, 99, 101, 21))
        self.label_39.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(50, 282, 61, 21))
        self.label_40.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(50, 253, 61, 21))
        self.label_41.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(50, 341, 111, 21))
        self.label_42.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(50, 224, 61, 21))
        self.label_43.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(50, 368, 111, 21))
        self.label_44.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")

        self.label_44.setObjectName("label_44")

        self.pedido = QtWidgets.QLabel(self.centralwidget)
        self.pedido.setGeometry(QtCore.QRect(20, 410, 230, 31))
        self.pedido.setObjectName("pedido")
        self.pedido.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")

        MainWindow.setCentralWidget(self.centralwidget)


        self.finalizar.setDisabled(True)
        self.finalizar.clicked.connect(self.finaliza)
        self.finalizar.clicked.connect(MainWindow.hide)

        self.ml_200.clicked.connect(self.hab_finaliza)
        self.ml_500.clicked.connect(self.hab_finaliza)
        self.ml_700.clicked.connect(self.hab_finaliza)
        self.chocolate.clicked.connect(self.hab_finaliza)
        self.morango.clicked.connect(self.hab_finaliza)
        self.nutella.clicked.connect(self.hab_finaliza)
        self.baunilha.clicked.connect(self.hab_finaliza)
        self.ovo_oreo.clicked.connect(self.hab_finaliza)
        self.chanti_cereja.clicked.connect(self.hab_finaliza)

        self.voltar.clicked.connect(self.volta)
        self.voltar.clicked.connect(MainWindow.hide)

        MainWindow.setFixedWidth(385)
        MainWindow.setFixedHeight(580)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def selecionado(self):
        if self.ml_200.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Morango {"200 ml"} R$ 5,00')
        if self.ml_500.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Morango {"500 ml"} R$ 10,00')
        if self.ml_700.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Morango {"700 ml"} R$ 15,00')

    def chocolateFunc(self):
        if self.ml_200.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Chocolate {"200 ml"} R$ 5,00')
        if self.ml_500.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Chocolate {"500 ml"} R$ 10,00')
        if self.ml_700.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Chocolate {"700 ml"} R$ 15,00')

    def baunilhaFunc(self):
        if self.ml_200.isChecked() and self.baunilha.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Baunilha {"200 ml"} R$ 5,00')
        if self.ml_500.isChecked() and self.baunilha.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Baunilha {"500 ml"} R$ 10,00')
        if self.ml_700.isChecked() and self.baunilha.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Baunilha {"700 ml"} R$ 15,00')

    def nutellaFunc(self):
        if self.ml_200.isChecked() and self.nutella.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Nutella {"200 ml"} R$ 5,00')
        if self.ml_500.isChecked() and self.nutella.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Nutella {"500 ml"} R$ 10,00')
        if self.ml_700.isChecked() and self.nutella.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Nutella {"700 ml"} R$ 15,00')

    def ml_200_Func(self):
        if self.ml_200.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Morango {"200 ml"} R$ 5,00')
        if self.ml_200.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Chocolate {"200 ml"} R$ 5,00')
        if self.ml_200.isChecked() and self.nutella.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Nutella {"200 ml"} R$ 5,00')
        if self.ml_200.isChecked() and self.baunilha.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Baunilha {"200 ml"} R$ 5,00')

    def ml_500_Func(self):
        if self.ml_500.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Morango {"500 ml"} R$ 10,00')
        if self.ml_500.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Chocolate {"500 ml"} R$ 10,00')
        if self.ml_500.isChecked() and self.nutella.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Nutella {"500 ml"} R$ 10,00')
        if self.ml_500.isChecked() and self.baunilha.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Baunilha {"500 ml"} R$ 10,00')

    def ml_700_Func(self):
        if self.ml_700.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Morango {"700 ml"} R$ 15,00')
        if self.ml_700.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Chocolate {"700 ml"} R$ 15,00')
        if self.ml_700.isChecked() and self.nutella.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Nutella {"700 ml"} R$ 15,00')
        if self.ml_700.isChecked() and self.baunilha.isChecked():
            self.pedido.setText(f'Pedido - Milkshake Baunilha {"700 ml"} R$ 15,00')


    def hab_finaliza(self):
        if self.ml_200.isChecked() or self.ml_500.isChecked() or self.ml_700.isChecked():
            if self.chocolate.isChecked() or self.baunilha.isChecked() or self.morango.isChecked() or self.nutella.isChecked():
                if self.ovo_oreo.isChecked() or self.chanti_cereja.isChecked():
                    self.finalizar.setDisabled(False)
    def finaliza(self):
        from pagamento import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.pagamento = Ui_MainWindow()
        self.pagamento.setupUi(self.janela)
        self.janela.show()
    def volta(self):
        from comprar import Ui_Comprar
        self.janela = QtWidgets.QMainWindow()
        self.comprar = Ui_Comprar()
        self.comprar.setupUi(self.janela)
        self.janela.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sabores de Milk Shake:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tamanhos:</span></p><p><span style=\" font-size:12pt; font-weight:600;\"><br/></span></p></body></html>"))
        self.finalizar.setText(_translate("MainWindow", "Finalizar"))
        self.label_32.setText(_translate("MainWindow", "Milk Shakes"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Complementos:</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>200 mL- R$ 5,00</p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p>Chocolate</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>700 mL - R$ 15,00</p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>500 mL - R$ 10,00</p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>Nutella</p><p><br/></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>Baunilha</p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p>Ovomaltene + Oreo</p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p>Morango</p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>Chantilly + Cereja</p></body></html>"))
        self.pedido.setText(_translate("MainWindow", "Pedido -"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
