# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sobre1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 580))
        self.label.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 371, 561))
        self.label_2.setStyleSheet("QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 91, 91))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(126, 66, 54);\n"
"border-radius:45px;\n"
"border: 3px solid rgb(126, 66, 54)\n"
"}")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 430, 91, 91))
        self.label_6.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: rgb(126, 66, 54);\n"
"border-radius:45px;\n"
"border: 3px solid rgb(126, 66, 54)\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 330, 91, 91))
        self.label_7.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: rgb(126, 66, 54);\n"
"border-radius:45px;\n"
"border: 3px solid rgb(126, 66, 54)\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 91, 91))
        self.label_8.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: rgb(126, 66, 54);\n"
"border-radius:45px;\n"
"border: 3px solid rgb(126, 66, 54)\n"
"}")
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 130, 91, 91))
        self.label_9.setStyleSheet("QLabel {\n"
"    \n"
"    background-color: rgb(126, 66, 54);\n"
"border-radius:45px;\n"
"border: 3px solid rgb(126, 66, 54)\n"
"}")
        self.label_9.setText("")
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(118, 20, 201, 31))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Bukhari Script\";")
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(118, 120, 191, 31))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Bukhari Script\";")
        self.label_10.setObjectName("label_10")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(113, 150, 261, 71))
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4 px solid rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";\n"
"}\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(118, 220, 261, 31))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Bukhari Script\";")
        self.label_11.setObjectName("label_11")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(113, 50, 261, 71))
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4 px solid rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";\n"
"}\n"
"")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(118, 320, 261, 31))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Bukhari Script\";")
        self.label_12.setObjectName("label_12")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(113, 350, 261, 71))
        self.textBrowser_4.setStyleSheet("QTextBrowser {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4 px solid rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";\n"
"}\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(118, 420, 261, 31))
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Bukhari Script\";")
        self.label_13.setObjectName("label_13")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(113, 450, 261, 71))
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4 px solid rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";\n"
"}\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(113, 250, 261, 71))
        self.textBrowser_6.setStyleSheet("QTextBrowser {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4 px solid rgb(255, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";\n"
"}\n"
"")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 91, 101))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSobre\Azul escuro.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 91, 101))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSobre\Verde.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 330, 91, 101))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSobre\Azulclaro.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 430, 91, 101))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSobre\Azul.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(16, 30, 101, 102))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSobre\prof.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(340, 16, 31, 31))
        self.voltar.setAutoFillBackground(False)
        self.voltar.setStyleSheet("QPushButton {\n"
                                  "background-color: rgb(126, 66, 54);\n"
                                  "border-radius: 15px;\n"
                                  "border: 1px solid rgb(0, 0, 0);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: rgb(150, 71, 56);\n"
                                  "}\n"
                                  "QPushButton:pressed {\n"
                                  "    \n"
                                  "    background-color: rgb(100, 66, 49);\n"
                                  "}")
        self.voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Voltar.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.voltar.setIcon(icon)
        self.voltar.setIconSize(QtCore.QSize(20, 25))
        self.voltar.setObjectName("voltar")
        self.voltar.clicked.connect(self.volta)
        self.voltar.clicked.connect(MainWindow.hide)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setFixedWidth(385)
        MainWindow.setFixedHeight(580)

    def volta(self):
        from inicio_sobre import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.comprar = Ui_MainWindow()
        self.comprar.setupUi(self.janela)
        self.janela.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Prof. Clayton Maciel</span><br/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Gabriel H. Ramalho</span></p><p><br/></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600;\">Aluno no Instituto Federal do Rio Grande do Norte / IFRN - Campus Mossoró e responsável pela ideia e execução do projeto</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Plácido da Silva</span></p><p><br/></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600;\">Aluno no Instituto Federal do Rio Grande do Norte / IFRN - Campus Mossoró e responsável pela interface do projeto</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Pedro E. Jales</span></p><p><br/></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600;\">Aluno no Instituto Federal do Rio Grande do Norte / IFRN - Campus Mossoró e responsável pelo design do projeto</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Robert de Oliveira</span><br/></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600;\">Aluno no Instituto Federal do Rio Grande do Norte / IFRN - Campus Mossoró e responsável pela programação do projeto</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600;\"><br /></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:600;\">Aluno no Instituto Federal do Rio Grande do Norte / IFRN - Campus Mossoró e responsável pela interface do projeto</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
