# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorvete4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 580))
        self.label.setMinimumSize(QtCore.QSize(391, 580))
        self.label.setMaximumSize(QtCore.QSize(391, 580))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 25, 50))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 25, 50))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 25, 50))
        self.label_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 0, 25, 50))
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 25, 50))
        self.label_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 0, 25, 50))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 0, 25, 50))
        self.label_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 0, 25, 50))
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 25, 50))
        self.label_10.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 0, 25, 50))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-5, 20, 461, 561))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\Fundo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 50, 121, 21))
        self.label_14.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 120, 161, 21))
        self.label_16.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_16.setObjectName("label_16")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 290, 101, 21))
        self.label_26.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_26.setObjectName("label_26")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(240, 170, 140, 140))
        self.label_31.setStyleSheet("")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSorvete\Sorvete.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(115, 520, 161, 41))
        self.label_32.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 28pt \"Bukhari Script\";")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(255, 460, 111, 131))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSorvete\Sorvetinho.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(19, 460, 111, 131))
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSorvete\Sorvetinho.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(350, 60, 31, 31))
        self.voltar.setAutoFillBackground(False)
        self.voltar.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voltar.setIcon(icon)
        self.voltar.setIconSize(QtCore.QSize(20, 25))
        self.voltar.setObjectName("voltar")
        self.finalizar = QtWidgets.QPushButton(self.centralwidget)
        self.finalizar.setGeometry(QtCore.QRect(260, 400, 101, 41))
        self.finalizar.setStyleSheet("QPushButton {\n"
"    color: rgb(247, 89, 113);\n"
"    font: 15pt \"Bukhari Script\";\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.finalizar.setObjectName("finalizar")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(40, 97, 104, 21))
        self.label_37.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_37.setObjectName("label_37")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 16, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.casquinhas = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.casquinhas.setContentsMargins(0, 0, 0, 0)
        self.casquinhas.setObjectName("casquinhas")
        self.pequena = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.pequena.setStyleSheet("font: 8pt \"Open Sans\";")
        self.pequena.setText("")
        self.pequena.setObjectName("pequena")
        self.pequena.clicked.connect(self.grandefunc)
        self.casquinhas.addWidget(self.pequena)
        self.grande = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.grande.setStyleSheet("font: 8pt \"Open Sans\";")
        self.grande.setText("")
        self.grande.clicked.connect(self.grandefunc)
        self.grande.setObjectName("grande")
        self.casquinhas.addWidget(self.grande)
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(40, 71, 104, 21))
        self.label_36.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_36.setObjectName("label_36")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 140, 192, 41))
        self.label_13.setStyleSheet("color: rgb(247, 89, 113);")
        self.label_13.setObjectName("label_13")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(40, 178, 61, 21))
        self.label_38.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_38.setObjectName("label_38")
        self.chocolate = QtWidgets.QCheckBox(self.centralwidget)
        self.chocolate.setGeometry(QtCore.QRect(20, 180, 16, 16))
        self.chocolate.setText("")
        self.chocolate.setObjectName("chocolate")
        self.morango = QtWidgets.QCheckBox(self.centralwidget)
        self.morango.setGeometry(QtCore.QRect(20, 210, 21, 17))
        self.morango.setText("")
        self.morango.setObjectName("morango")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(40, 208, 61, 21))
        self.label_39.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_39.setObjectName("label_39")
        self.nutella = QtWidgets.QCheckBox(self.centralwidget)
        self.nutella.setGeometry(QtCore.QRect(20, 240, 21, 17))
        self.nutella.setText("")
        self.nutella.setObjectName("nutella")
        self.flocos = QtWidgets.QCheckBox(self.centralwidget)
        self.flocos.setGeometry(QtCore.QRect(20, 270, 21, 17))
        self.flocos.setText("")
        self.flocos.setObjectName("flocos")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(40, 268, 61, 21))
        self.label_40.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(40, 238, 61, 21))
        self.label_41.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(130, 178, 71, 21))
        self.label_42.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_42.setObjectName("label_42")
        self.ovo = QtWidgets.QCheckBox(self.centralwidget)
        self.ovo.setGeometry(QtCore.QRect(110, 240, 21, 17))
        self.ovo.setText("")
        self.ovo.setObjectName("ovo")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(130, 238, 71, 21))
        self.label_43.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_43.setObjectName("label_43")
        self.coco = QtWidgets.QCheckBox(self.centralwidget)
        self.coco.setGeometry(QtCore.QRect(110, 270, 21, 17))
        self.coco.setText("")
        self.coco.setObjectName("coco")
        self.cacau = QtWidgets.QCheckBox(self.centralwidget)
        self.cacau.setGeometry(QtCore.QRect(110, 180, 16, 16))
        self.cacau.setText("")
        self.cacau.setObjectName("cacau")
        self.baunilha = QtWidgets.QCheckBox(self.centralwidget)
        self.baunilha.setGeometry(QtCore.QRect(110, 210, 21, 17))
        self.baunilha.setText("")
        self.baunilha.setObjectName("baunilha")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(130, 268, 71, 21))
        self.label_44.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(130, 208, 71, 21))
        self.label_45.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_45.setObjectName("label_45")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 310, 21, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.coberturas = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.coberturas.setContentsMargins(0, 0, 0, 0)
        self.coberturas.setObjectName("coberturas")
        self.morango_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.morango_2.setText("")
        self.morango_2.setObjectName("morango_2")
        self.coberturas.addWidget(self.morango_2)
        self.choco_leite = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.choco_leite.setText("")
        self.choco_leite.setObjectName("choco_leite")
        self.coberturas.addWidget(self.choco_leite)
        self.nutella_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.nutella_2.setText("")
        self.nutella_2.setObjectName("nutella_2")
        self.coberturas.addWidget(self.nutella_2)
        self.leite_conde = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.leite_conde.setText("")
        self.leite_conde.setObjectName("leite_conde")
        self.coberturas.addWidget(self.leite_conde)
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(40, 311, 104, 21))
        self.label_46.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_46.setObjectName("label_46")
        self.seilacaguei = QtWidgets.QLabel(self.centralwidget)
        self.seilacaguei.setGeometry(QtCore.QRect(40, 361, 104, 21))
        self.seilacaguei.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.seilacaguei.setObjectName("seilacaguei")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(40, 386, 104, 21))
        self.label_48.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(40, 336, 104, 21))
        self.label_49.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")

        self.label_49.setObjectName("label_49")

        self.pedido = QtWidgets.QLabel(self.centralwidget)
        self.pedido.setGeometry(QtCore.QRect(20, 410, 230, 31))
        self.pedido.setObjectName("pedido")
        self.pedido.setStyleSheet("\n"
                                  "QLabel {\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "border: 4px solid rgb(85, 255, 255);\n"
                                  "color: rgb(247, 89, 113);\n"
                                  "}\n"
                                  "")

        MainWindow.setCentralWidget(self.centralwidget)

        self.finalizar.setDisabled(True)
        self.finalizar.clicked.connect(self.finaliza)
        self.finalizar.clicked.connect(MainWindow.hide)

        self.chocolate.clicked.connect(self.grandefunc)
        self.morango.clicked.connect(self.grandefunc)
        self.nutella.clicked.connect(self.grandefunc)
        self.flocos.clicked.connect(self.grandefunc)
        self.cacau.clicked.connect(self.grandefunc)
        self.baunilha.clicked.connect(self.grandefunc)
        self.ovo.clicked.connect(self.grandefunc)
        self.coco.clicked.connect(self.grandefunc)

        self.pequena.clicked.connect(self.hab_finaliza)
        self.grande.clicked.connect(self.hab_finaliza)

        self.chocolate.clicked.connect(self.sabores)
        self.morango.clicked.connect(self.sabores)
        self.nutella.clicked.connect(self.sabores)
        self.flocos.clicked.connect(self.sabores)
        self.cacau.clicked.connect(self.sabores)
        self.baunilha.clicked.connect(self.sabores)
        self.ovo.clicked.connect(self.sabores)
        self.coco.clicked.connect(self.sabores)

        self.chocolate.clicked.connect(self.hab_finaliza)
        self.morango.clicked.connect(self.hab_finaliza)
        self.nutella.clicked.connect(self.hab_finaliza)
        self.flocos.clicked.connect(self.hab_finaliza)
        self.cacau.clicked.connect(self.hab_finaliza)
        self.baunilha.clicked.connect(self.hab_finaliza)
        self.ovo.clicked.connect(self.hab_finaliza)
        self.coco.clicked.connect(self.hab_finaliza)

        self.morango_2.clicked.connect(self.hab_finaliza)
        self.choco_leite.clicked.connect(self.hab_finaliza)
        self.nutella_2.clicked.connect(self.hab_finaliza)
        self.leite_conde.clicked.connect(self.hab_finaliza)

        self.voltar.clicked.connect(self.volta)
        self.voltar.clicked.connect(MainWindow.hide)

        MainWindow.setFixedWidth(385)
        MainWindow.setFixedHeight(580)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def grandefunc(self):
        if self.pequena.isChecked() or self.grande.isChecked():
            quant = 0
            if self.chocolate.isChecked():
                quant += 1
            if self.morango.isChecked():
                quant += 1
            if self.nutella.isChecked():
                quant += 1
            if self.flocos.isChecked():
                quant += 1
            if self.cacau.isChecked():
                quant += 1
            if self.baunilha.isChecked():
                quant += 1
            if self.ovo.isChecked():
                quant += 1
            if self.coco.isChecked():
                quant += 1
            if quant == 2 and self.grande.isChecked():
                self.pedido.setText(f'Pedido - Casquinha G. dois sabores R$ 4,00')
            elif quant == 2 and self.pequena.isChecked():
                self.pedido.setText(f'Pedido - Casquinha P. dois sabores R$ 2,00')
            if quant == 1 and self.grande.isChecked():
                self.pedido.setText(f'Pedido - Casquinha G. um sabor R$ 4,00')
            elif quant == 1 and self.pequena.isChecked():
                self.pedido.setText(f'Pedido - Casquinha P. um sabor R$ 2,00')

    def hab_finaliza(self):
        if self.pequena.isChecked() or self.grande.isChecked():
            quant = 0
            if self.chocolate.isChecked():
                quant += 1
            if self.morango.isChecked():
                quant += 1
            if self.nutella.isChecked():
                quant += 1
            if self.flocos.isChecked():
                quant += 1
            if self.cacau.isChecked():
                quant += 1
            if self.baunilha.isChecked():
                quant += 1
            if self.ovo.isChecked():
                quant += 1
            if self.coco.isChecked():
                quant += 1
            if quant == 2 or quant == 1:
                self.finalizar.setDisabled(False)
            if quant == 0:
                self.finalizar.setDisabled(True)
    def finaliza(self):
        from pagamento import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.pagamento = Ui_MainWindow()
        self.pagamento.setupUi(self.janela)
        self.janela.show()
    def volta(self):
        from comprar import Ui_Comprar
        self.janela = QtWidgets.QMainWindow()
        self.comprar = Ui_Comprar()
        self.comprar.setupUi(self.janela)
        self.janela.show()
    def sabores(self):
        quant = 0
        if self.chocolate.isChecked():
            quant += 1
        if self.morango.isChecked():
            quant += 1
        if self.nutella.isChecked():
            quant += 1
        if self.flocos.isChecked():
            quant += 1
        if self.cacau.isChecked():
            quant += 1
        if self.baunilha.isChecked():
            quant += 1
        if self.ovo.isChecked():
            quant += 1
        if self.coco.isChecked():
            quant += 1
        if quant == 2:
            if self.chocolate.isChecked() == False:
                self.chocolate.setDisabled(True)
            if self.morango.isChecked() == False:
                self.morango.setDisabled(True)
            if self.ovo.isChecked() == False:
                self.ovo.setDisabled(True)
            if self.nutella.isChecked() == False:
                self.nutella.setDisabled(True)
            if self.flocos.isChecked() == False:
                self.flocos.setDisabled(True)
            if self.cacau.isChecked() == False:
                self.cacau.setDisabled(True)
            if self.baunilha.isChecked() == False:
                self.baunilha.setDisabled(True)
            if self.coco.isChecked() == False:
                self.coco.setDisabled(True)
        if quant < 2:
            self.chocolate.setDisabled(False)
            self.morango.setDisabled(False)
            self.nutella.setDisabled(False)
            self.flocos.setDisabled(False)
            self.cacau.setDisabled(False)
            self.baunilha.setDisabled(False)
            self.ovo.setDisabled(False)
            self.coco.setDisabled(False)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Casquinhas:</span></p><p><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sabores de Sorvete:</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Coberturas:</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "Sorvetes"))
        self.finalizar.setText(_translate("MainWindow", "Finalizar"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p>Grande - R$ 4,00</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>Pequena - R$ 2,00</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">*independentemente da casquinha, só podem </span></p><p><span style=\" font-size:7pt;\">ser escolhidos dois sabores*</span></p><p><span style=\" font-size:7pt;\"><br/></span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Chocolate</p><p><br/></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>Morango</p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>Flocos</p><p><br/></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>Nutella</p><p><br/></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p>Cacau 70%</p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p>Ovomaltene</p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p>Coco</p><p><br/></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p>Baunilha</p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p>Morango</p><p><br/></p></body></html>"))
        self.seilacaguei.setText(_translate("MainWindow", "<html><head/><body><p>Nutella</p><p><br/></p><p><br/></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p>Leite Condensado</p></body></html>"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p>Chocolate ao Leite</p></body></html>"))
        self.pedido.setText(_translate("MainWindow", "Pedido -"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
