# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sundae4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, parent_obj=None):
        self.parent_obj = parent_obj
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 580)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 391, 580))
        self.label.setMinimumSize(QtCore.QSize(391, 580))
        self.label.setMaximumSize(QtCore.QSize(391, 580))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 25, 50))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 25, 50))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-5, 20, 461, 561))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\Fundo.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 140, 191, 21))
        self.label_16.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_16.setObjectName("label_16")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 0, 25, 50))
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 0, 25, 50))
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 25, 50))
        self.label_4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 0, 25, 50))
        self.label_8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 0, 25, 50))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 25, 50))
        self.label_10.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 50, 121, 21))
        self.label_14.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_14.setObjectName("label_14")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(200, 109, 211, 211))
        self.label_31.setStyleSheet("")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Sundae.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.finalizar = QtWidgets.QPushButton(self.centralwidget)
        self.finalizar.setGeometry(QtCore.QRect(260, 400, 101, 41))
        self.finalizar.setStyleSheet("QPushButton {\n"
"    color: rgb(247, 89, 113);\n"
"    font: 15pt \"Bukhari Script\";\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.finalizar.setObjectName("finalizar")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 0, 25, 50))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(120, 520, 151, 41))
        self.label_32.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 28pt \"Bukhari Script\";")
        self.label_32.setObjectName("label_32")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 250, 141, 21))
        self.label_26.setStyleSheet("color: rgb(247, 89, 113);\n"
"font: 8pt \"Open Sans\";")
        self.label_26.setObjectName("label_26")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 0, 25, 50))
        self.label_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(266, 485, 71, 91))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Sundae_rosa.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(50, 485, 71, 91))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Sundae_rosa.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(350, 60, 31, 31))
        self.voltar.setAutoFillBackground(False)
        self.voltar.setStyleSheet("QPushButton {\n"
"background-color: rgb(126, 66, 54);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(150, 71, 56);\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(100, 66, 49);\n"
"}")
        self.voltar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\Projeto icy cream\imagens\TelaSundae\Voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voltar.setIcon(icon)
        self.voltar.setIconSize(QtCore.QSize(20, 25))
        self.voltar.setObjectName("voltar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 16, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tamanhos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tamanhos.setContentsMargins(0, 0, 0, 0)
        self.tamanhos.setObjectName("tamanhos")
        self.ml_250 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_250.setStyleSheet("")
        self.ml_250.setText("")
        self.ml_250.setObjectName("ml_250")
        self.ml_250.clicked.connect(self.ml_200_Func)
        self.tamanhos.addWidget(self.ml_250)

        self.ml_375 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.ml_375.setStyleSheet("")
        self.ml_375.setText("")
        self.ml_375.setObjectName("ml_375")
        self.ml_375.clicked.connect(self.ml_500_Func)
        self.tamanhos.addWidget(self.ml_375)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 160, 16, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sabores = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.sabores.setContentsMargins(0, 0, 0, 0)
        self.sabores.setSpacing(6)
        self.sabores.setObjectName("sabores")

        self.chocolate = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.chocolate.setStyleSheet("")
        self.chocolate.setText("")
        self.chocolate.setObjectName("chocolate")
        self.chocolate.clicked.connect(self.chocolateFunc)
        self.sabores.addWidget(self.chocolate)

        self.morango = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.morango.setStyleSheet("")
        self.morango.setText("")
        self.morango.setObjectName("morango")
        self.morango.clicked.connect(self.morangofunc)
        self.sabores.addWidget(self.morango)

        self.doce_leite = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.doce_leite.setStyleSheet("")
        self.doce_leite.setText("")
        self.doce_leite.setObjectName("doce_leite")
        self.doce_leite.clicked.connect(self.docedeleitefunc)
        self.sabores.addWidget(self.doce_leite)

        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 270, 16, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.complementos = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.complementos.setContentsMargins(0, 0, 0, 0)
        self.complementos.setObjectName("complementos")
        self.amendoin = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.amendoin.setStyleSheet("")
        self.amendoin.setText("")
        self.amendoin.setObjectName("amendoin")
        self.complementos.addWidget(self.amendoin)
        self.oreo = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.oreo.setStyleSheet("")
        self.oreo.setText("")
        self.oreo.setObjectName("oreo")
        self.complementos.addWidget(self.oreo)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(40, 73, 101, 21))
        self.label_29.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(40, 189, 91, 21))
        self.label_30.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(40, 97, 101, 21))
        self.label_33.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(40, 163, 91, 21))
        self.label_34.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(40, 297, 101, 21))
        self.label_35.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(40, 273, 101, 21))
        self.label_36.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.label_36.setObjectName("label_36")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(40, 216, 91, 21))
        self.label_38.setStyleSheet("\n"
"QLabel {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 4px solid rgb(85, 255, 255);\n"
"color: rgb(247, 89, 113);\n"
"}\n"
"")
        self.pedido = QtWidgets.QLabel(self.centralwidget)
        self.pedido.setGeometry(QtCore.QRect(20, 410, 230, 31))
        self.pedido.setObjectName("pedido")
        self.pedido.setStyleSheet("\n"
                                  "QLabel {\n"
                                  "background-color: rgb(255, 255, 255);\n"
                                  "border: 4px solid rgb(85, 255, 255);\n"
                                  "color: rgb(247, 89, 113);\n"
                                  "}\n"
                                  "")

        self.label_38.setObjectName("label_38")
        MainWindow.setCentralWidget(self.centralwidget)

        self.finalizar.setDisabled(True)

        self.voltar.clicked.connect(self.volta)
        self.voltar.clicked.connect(MainWindow.hide)

        self.ml_375.clicked.connect(self.hab_finaliza)
        self.ml_250.clicked.connect(self.hab_finaliza)
        self.chocolate.clicked.connect(self.hab_finaliza)
        self.morango.clicked.connect(self.hab_finaliza)
        self.doce_leite.clicked.connect(self.hab_finaliza)
        self.amendoin.clicked.connect(self.hab_finaliza)
        self.oreo.clicked.connect(self.hab_finaliza)

        self.finalizar.clicked.connect(self.finaliza)
        self.finalizar.clicked.connect(MainWindow.hide)

        self.chocolate.clicked.connect(self.sabor)
        self.morango.clicked.connect(self.sabor)
        self.doce_leite.clicked.connect(self.sabor)

        self.amendoin.clicked.connect(self.cobertura)
        self.oreo.clicked.connect(self.cobertura)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setFixedWidth(385)
        MainWindow.setFixedHeight(580)

    def morangofunc(self):
        if self.ml_250.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Sundae Morango 250ml R$ 4,00')
        if self.ml_375.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Sundae Morango 375ml R$ 6,00')

    def chocolateFunc(self):
        if self.ml_250.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Sundae Chocolate 250ml R$ 4,00')
        if self.ml_375.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Sundae Chocolate 375ml R$ 6,00')


    def docedeleitefunc(self):
        if self.ml_250.isChecked() and self.doce_leite.isChecked():
            self.pedido.setText(f'Pedido - Sundae Doce de Leite 250ml R$ 4,00')
        if self.ml_375.isChecked() and self.doce_leite.isChecked():
            self.pedido.setText(f'Pedido - Sundae Doce de Leite 375ml R$ 6,00')

    def ml_200_Func(self):
        if self.ml_250.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Sundae Morango  250 ml R$ 4,00')
        if self.ml_250.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Sundae Chocolate  250 ml R$ 4,00')
        if self.ml_250.isChecked() and self.doce_leite.isChecked():
            self.pedido.setText(f'Pedido - Sundae Doce de Leite  250 ml R$ 4,00')

    def ml_500_Func(self):
        if self.ml_375.isChecked() and self.morango.isChecked():
            self.pedido.setText(f'Pedido - Sundae Morango  375 ml R$ 6,00')
        if self.ml_375.isChecked() and self.chocolate.isChecked():
            self.pedido.setText(f'Pedido - Sundae chocolate  375 ml R$ 6,00')
        if self.ml_375.isChecked() and self.doce_leite.isChecked():
            self.pedido.setText(f'Pedido - Sundae Doce de Leite  375 ml R$ 6,00')

    def hab_finaliza(self):
        if self.ml_375.isChecked() or self.ml_250.isChecked():
            if self.chocolate.isChecked() or self.morango.isChecked() or self.doce_leite.isChecked():
                if self.amendoin.isChecked() or self.oreo.isChecked():
                    self.finalizar.setDisabled(False)
    def finaliza(self):
        from pagamento import Ui_MainWindow
        self.janela = QtWidgets.QMainWindow()
        self.pagamento = Ui_MainWindow()
        self.pagamento.setupUi(self.janela)
        self.janela.show()
    def sabor(self):
        if self.chocolate.isChecked():
            pass
        elif self.morango.isChecked():
            pass
        elif self.doce_leite.isChecked():
            pass
        else:
            pass
    def cobertura(self):
        if self.amendoin.isChecked():
            pass
        elif self.oreo.isChecked():
            pass
        else:
            pass
    def volta(self):
        from comprar import Ui_Comprar
        self.janela = QtWidgets.QMainWindow()
        self.comprar = Ui_Comprar()
        self.comprar.setupUi(self.janela)
        self.janela.show()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sabores de Sundaes:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tamanhos:</span></p><p><span style=\" font-size:12pt; font-weight:600;\"><br/></span></p></body></html>"))
        self.finalizar.setText(_translate("MainWindow", "Finalizar"))
        self.label_32.setText(_translate("MainWindow", "Sundaes"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Complementos:</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p>250 mL- R$ 4,00</p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>Morango</p><p><br/></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p>375 mL - R$ 6,00</p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p>Chocolate</p><p><br/></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p>Oreo</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>Amendoin</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>Doce de Leite</p><p><br/></p></body></html>"))
        self.pedido.setText(_translate("MainWindow", "Pedido -"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
